title: "mpoegel_io"
description: "personal portfolio and blog"
url: "mpoegel.github.io"

author:
  name     : "Matt Poegel"
  url      : mpoegel.github.io
  facebook : https://www.facebook.com/matt.poegel
  twitter  : https://twitter.com/KidFromCary

github: https://github.com/mpoegel

paginate: 3
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
highlighter: rouge
encoding: utf-8

gems: [jekyll-paginate]
